### PR TITLE
require non-slow babel-generator

### PR DESCRIPTION
**Pull request by graingert**
Fixes https://github.com/istanbuljs/babel-plugin-istanbul/issues/5

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by bcoe** [comment]
@graingert great! since we're using the `^` this should be pulled in automatically for folks, but I always like to be explicit.

Have you noticed a significant performance improvement with this update?

**Comment by graingert** [comment]
@bcoe actually, not really.

babel-plugin-__coverage__ takes 11.87s user 0.50s system 108% cpu 11.443 total
babel-plugin-istanbul takes 34.14s user 0.24s system 102% cpu 33.612 total
no transpiler takes 6.81s user 0.28s system 110% cpu 6.396 total

**Comment by graingert** [comment]
3.47 seconds extra is quite a bit

**Comment by bcoe** [comment]
@graingert those benchmarks suggest we're on par with `__coverage__` now however?

**Comment by graingert** [comment]
@bcoe yep, it would be great to merge this in so I can force the new version

**Comment by bcoe** [comment]
@graingert if you don't mind, give `1.1.0-alpha.4` a spin and make sure it does the trick for you; if so we should update `nyc`, and `babel-plugin-istanbul` accordingly. I'll happily accept a patch on both repos ... I need to run and walk my puppy, so OSS chore time is over for the evening.

**Pull request merged**
