### PR TITLE
Instrumentation API/ visitor using babel

### PR DESCRIPTION
**Pull request by gotwarlost**
Opening a PR so people can provide source level feedback. Still TODO:

* simplify tests
* make `for` index updates and assignment patterns branches rather than statements
* Add more es6 tests
* Compute coverage for tests
* document breaking changes in README

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by gotwarlost** [comment]
Known bugs:

* source map production fails somewhere in `babel-generate` need to track down why
* generating `non-compact` source code takes forever. Something in `babel-generate` as well.

@istanbuljs/instrumentation-owners - please take a look

**Comment by bcoe** [comment]
@gotwarlost experimenting with wiring this up to `nyc`, would I use a similar approach as with `__coverage__` -- add this as an additional babel plugin?

**Comment by bcoe** [comment]
@gotwarlost did some initial testing creating a babel plugin that looks something like this:

```js
var ili = require('istanbul-lib-instrument')

module.exports = function (t) {
  return {
    visitor: {
      Program: new ili.programVisitor(t.types)
    }
  }
}
```

It seems to instrument the ES2015 code, as one would expect:

```js
var Yarsay = (++__cov_6HLW3wgYL4dOZHpMIxoHRvvKytw.s['1'], require('../src/yarsay'));
```

But in the context of the instrumented code, the global counter variable seems to not be defined:

```js
ReferenceError: __cov_6HLW3wgYL4dOZHpMIxoHRvvKytw is not defined
```

**Comment by gotwarlost** [comment]
@bcoe the thing is that you need to invoke `programVisitor` for every file since it explicitly doesn't want to know about babel state.

 Something like this gist:
https://gist.github.com/gotwarlost/e203dff7e14bb8234fb8c48db5a61d7a

**Comment by gotwarlost** [comment]
@bcoe there was also a problem with the variable declaration that i fixed.

**Comment by bcoe** [comment]
## Babel Plugin

@gotwarlost babel plugin based approach seems to be working like a charm:

screen shot 2016-06-22 at 8 40 51 pm

@dtinth how would you feel about combining forces and creating a plugin: `babel-plugin-istanbul`, @gotwarlost could you create a repository with this name, it would be good to grab this namespace in npm.

## Babel Instrumenter

@gotwarlost I'm going to move on and test this module as a replacement instrumenter in `nyc`, rather than running it as a plugin.

**Comment by bcoe** [comment]
## Babel Instrumenter

I've tested the new instrumentation API, as one would expect, seems to do the trick:

screen shot 2016-06-22 at 11 05 05 pm

* as one would expect, it continues to have some issues with SourceMaps + ES2015 (I'm pretty sure something is getting lost in translation when remapping back to the appropriate line #s.
* in this new world of instrumentation being pulled out into its own module, how can I pull this off? `istanbul.config.loadFile(configFile).instrumentation.config` -- it would be nice to still support the `.istanbul.yml` config.

**Comment by gotwarlost** [comment]
I created a babel issue for the spurious source mappings.

https://phabricator.babeljs.io/T7453

**Comment by gotwarlost** [comment]
@bcoe - about the config file.

I'm working on a doc that has the changes for instrumentation options, including deleted options, new options and options with semantics changes. Once that is documented, we need to fix the config file for the new options. Then that part can still be passed to the instrument API. We can also pass the same opts to the `programVisitor` and it will use the subset of those options that are relevant to the babel world (for example, "compact" code generation, producing source maps etc. are controlled at the babel level and not relevant for the plugin)

**Comment by gotwarlost** [comment]
Added a git repo and an npm package for babel-plugin-istanbul. Squatting is complete :)

@dtinth is the author of the new plugin to maintain original credit. I hope he can find some time to actually port the code over :)

https://github.com/istanbuljs/babel-plugin-istanbul
https://www.npmjs.com/package/babel-plugin-istanbul

**Comment by gotwarlost** [comment]
More investigation on the bad source maps. I've convinced myself that I was on the right track with my findings which seem to be indeed the root cause of the bad branch colorings.

https://phabricator.babeljs.io/T7453#79702

**Comment by gotwarlost** [comment]
OK. I think I'm done. All tests pass, all TODO items done and coverage is pretty good.

If no one has any objections I'd like to merge this code and release `1.1.x-alpha` into the wild to get some real world feedback.

Source level PR comments are still welcome!

```
=============================== Coverage summary ==============================
Statements   : 99.19% ( 246/248 )
Branches     : 95.54% ( 107/112 )
Functions    : 100% ( 36/36 )
Lines        : 99.19% ( 246/248 )
=============================================================================
```

**Comment by dtinth** [comment]
Hello, and sorry for being inactive. I’ve been busy with other stuff.

It’s really great seeing that now Istanbul is offering a first-class Babel support. 🎉
More than 400 lines of code blasted, that’s very impressive. 😮 

Sorry that I didn’t have time to help port my plugin to Istanbul codebase. The goal of `babel-plugin-__coverage__` is to solve a very specific problem: Making Istanbul work with any code transpilable by Babel. I think the plugin already accomplished that goal, and I wasn’t ready to take any extra responsibility. I’ve got a lot of other crazy things that I want to spend my time building.

I’m very happy to see that the little plugin I wrote to solve my own problems has become beneficial to help developing a first-class ES support in Istanbul. That’s much better that what I did. 😃

Please let me know when Istanbul v2 is out, so I can mark my plugin as deprecated and point people there. No more strange versioning scheme! 😛

**Comment by bcoe** [comment]
@dtinth @gotwarlost I'm happy to help get the new plugin out the door. I've got an OSS programming weekend planned, and I'd like to get a nyc switched to Istanbul for Babel.

@dtinth I think we can at least make sure that we call you out in the README.md, your approach to managing ES2015 transforms is elegant and deserves credit.

@gotwarlost how do you feel about me pulling nyc into the istanbul org? If we're sanctioning it as the CLI for istanbul, I think it's time that it live here.

**Comment by gotwarlost** [comment]
@bcoe if you can take this on that will be great.

The README already credits @dtinth . 

@dtinth - thanks for all the good work on the plugin. i understand if you don't want to maintain it full time.

@bcoe I was going to suggest moving nyc to the istanbul org anyway. Please feel free to move it. I'll make you an  admin of the istanbul org.

**Comment by gotwarlost** [comment]
I'm merging this as-is and releasing a version in the wild for community feedback.

`node_modules` size for dependencies is now 58MB as opposed to 24MB using esprima. People might yell about this :(

**Comment by bcoe** [comment]
@gotwarlost curious, are the babel dependencies required for the built assets? couldn't the babel dependencies be dev only?

**Comment by gotwarlost** [comment]
Yeah, for the backwards compatible instrumenter API (needed for other-than-Babel) I need to essentially replicate something of what Babel does so I do need the parser, code generator and the traverse library.

This affects non-Babel users since the others would be asking for these deps anyway via Babel and hopefully they will be the same version such that multiple versions of these libraries are not required.

**Comment by bcoe** [comment]
@gotwarlost gotcha, so the reduced lines of code are because you're using a babel module, rather than your own logic -- seems smart to share this logic.

**Comment by gotwarlost** [comment]
OK I screwed the pooch with the first release. Luckily I updated the minor version so no one should have been affected.

Now `istanbul@1.1.0-alpha.1` -> `istanbul-api@1.1.0-alpha.1` -> `istanbul-lib-instrument@1.1.0-alpha.1`
can be used by folks currently using istanbul v1 for the new instrumentation library.

Now the babel plugin can also be implemented now that we have this lib in npm.

**Comment by bcoe** [comment]
@gotwarlost awesome, I plan on coding all day tomorrow, so I'm going to dive in and work on getting nyc transferred over here, starting with replacing `babel-plugin-__coverage__` with `babel-plugin-istanbul` -- I'll probably write a post on this.

**Comment by gotwarlost** [comment]
@bcoe - that will be awesome. Thanks!

**Pull request merged**
