### PR TITLE
Fix location for default args, add paranoid check for funcdecl, add render perf test

### PR DESCRIPTION
**Pull request by gotwarlost**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by gotwarlost** [comment]
Merging these fixes.

**Comment by bcoe** [comment]
@gotwarlost going to go ahead and publish this, and follow up on the issue on `__coverage__`.

**Comment by gotwarlost** [comment]
@bcoe - i was in the middle of doing this too :)

**Comment by bcoe** [comment]
@gotwarlost awesome, I'm testing in `babel-plugin-istanbul` now., and will have  patch release up shortly.

**Pull request merged**
