### PR TITLE
Use zero-based numeric indices for much faster instrumented code

### LINKED ISSUE #21: Faster instrumented code
Continuation of https://github.com/gotwarlost/istanbul/pull/694 will allow running coverage with almost no overhead, compared to the current situation of instrumented code running 4-5x slower than original, a huge problem in large projects.

The only question I have before I start a PR on this is what option to choose among the following:

1. Change the produced coverage JSON format so that `statements: {'1': 1, '2': 1, '3': 0}` become `statements: [1, 1, 0]`. How much of a breaking change this is and will it also require breaking changes in downstream modules?
2. Change the JSON format during instrumented run but convert it back to the old format in the end. Keeps compatibility but hackish and can lead to ugly code.
3. Try changing the format to use zero indexes (e.g. `statements: {'0': 1, '1': 1, '2': 0}`) — this might be enough to make V8 switch to "fast" mode where it treats it as array rather than dictionary — needs to be checked though.

I'd prefer option 1 but would appreciate hints on the scope of work here. cc @bcoe 

**update**: went with option 3 (zero-based indices).

Thanks!

### PR DESCRIPTION
**Pull request by mourner**
Closes #21. Makes instrumented code run much faster by making V8 use “fast” mode when accessing stats objects, which wasn't triggered before because of non-0-based indices.

Here's are the timings from [mapbox-gl-js render suite](https://github.com/mapbox/mapbox-gl-js):

- **no coverage**: 1m 6s
- **nyc current**: 4m 37s (or 3m 31s overhead)
- **nyc updated**: 1m 20s (or 14s overhead)

So, basically the performance overhead is 15 times smaller, down from 320% to 20%.

- [x] update tests

cc @bcoe @mramato

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mourner** [comment]
@bcoe Travis passes, so this ready to go.

**Comment by mourner** [comment]
@bcoe @gotwarlost anything I could help with to get this merged? A 15x speedup seems like something that's worth prioritizing. :)

**Comment by dmitriiabramov** [comment]
this is amazing! ❤️

**Comment by bcoe** [comment]
@dmitriiabramov @mourner I see no reason not to land this; but since I haven't heard back from @gotwarlost, I will be testing quite throughly; I'll start by publishing this to a `next` tag.

**Comment by bcoe** [comment]
@mourner I've published these changes to the `next` tag on npm, if you'd like to help test a bit:

`npm cache clear; npm i istanbul-lib-instrument@next`

**Comment by cpojer** [comment]
Oh this is awesome! Is anyone interested in trying this out on https://github.com/facebook/jest itself? :) (run jest with --coverage).

**Comment by mramato** [comment]
Thanks @mourner, I would love to try this out to confirm my issue in https://github.com/gotwarlost/istanbul/issues/556 is gone.  Unfortunately I currently rely on https://github.com/karma-runner/karma-coverage which hasn't updated to this library yet (but I'm hoping it happens soon or I can open a PR to do it for them).

**Comment by dmitriiabramov** [comment]
@cpojer i tested it on jest itself, but we don't really instrument much code, so there isn't much we can optimize :)
although it seems to run 1 second faster, 28s on average instead of 29s

**Comment by mourner** [comment]
@bcoe thanks! The new version works perfectly in our project:

- [no coverage](https://circleci.com/gh/mapbox/mapbox-gl-js/4615) — `test.sh` takes 4m53s
- [nyc latest](https://circleci.com/gh/mapbox/mapbox-gl-js/4906) — `test.sh` takes 11m22s
- [nyc new](https://circleci.com/gh/mapbox/mapbox-gl-js/4908) — `test.sh` takes 5m56s

**Comment by gotwarlost** [comment]
So sorry about my lack of response (this is getting old :( )

I see no reason off the top of my head why this should not be merged. 👍

**Comment by gotwarlost** [comment]
ah, it is merged already. Great.

**Pull request merged**
