### PR TITLE
feat: adds method for fetching instrumentation preamble

### PR DESCRIPTION
**Pull request by bcoe**
nyc used the `getPreamble` method exposed in the old istanbul instrumentation as a way to support adding all files:

```js
glob.sync(pattern, {cwd: this.cwd, nodir: true, ignore: this.exclude.exclude}).forEach(function (filename) {
    var obj = _this.addFile(path.join(_this.cwd, filename))
    if (obj.instrument) {
      module._compile(
        _this.instrumenter().getPreamble(obj.content, obj.relFile),
        filename
      )
    }
  })
```

This pull request exposes a similar method on the new API.

## Concerns

Adding all files seems a little bit slow, @gotwarlost can you think of any potential performance enhancements, or a better way for me to implement this functionality?

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by gotwarlost** [comment]
Not sure I'm in favor of exposing a `getPreamble` method. 

If I understand the use-case, you want to show empty coverage for files not required in tests? 

The way `istanbul-api` does it is like so: https://github.com/istanbuljs/istanbul-api/blob/master/lib/run-cover.js#L52-61

Which is, roughly:

1. The require hook usually does the thing of instrumenting the code and returning it.
2. When the hook is "disabled", it calls the instrumenter as usual, gets the file coverage object from the instrumenter, stuffs it into the global object and returns innocuous code that doesn't affect coverage numbers at all.
3. The "include all files" logic simply sets the "fake" flag and `require`-s all files without affecting any coverage numbers. 

https://github.com/istanbuljs/istanbul-api/blob/master/lib/run-cover.js#L131-L138

Would doing something like this work in nyc? Also, we need to reconcile nyc logic and the `istanbul-api` library and figure out what needs to exist where - and if istanbul-api should be stripped of things that nyc will never need.

**Comment by bcoe** [comment]
@gotwarlost I'd much rather not have to play around with the preamble, if we can figure out an alternative approach.

**Comment by bcoe** [comment]
@gotwarlost https://github.com/istanbuljs/nyc/commit/7f2b32e06efe881de65d3ec9fc46514c1f49d452

**Comment by gotwarlost** [comment]
@bcoe how about this. We add a new option to the program visitor called `fakeIt`, `noop` or whatever such that the `onExit` of the program visitor **replaces** the body of the program with just the preamble instead of inserting it. So, when the generated code it executed / require-d, it only does the side-effect processing of the preamble and does not execute any original code. This way we don't need a semantically ambiguous `getPreamble` and everything goes through the same code paths.

**Pull request closed without merging**
