### PR TITLE
Guard against invalid loc

### PR DESCRIPTION
**Pull request by tuckerconnelly**
Addresses https://github.com/istanbuljs/babel-plugin-istanbul/issues/22

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by bcoe** [comment]
@tuckerconnelly haven't forgotten about this, going to be landing some pull requests tonight hopefully.

**Comment by jseminck** [comment]
Any update on this? We have the same problem, and this PR fixes our issue.

**Comment by bcoe** [comment]
@jseminck merging, but I won't be able to release a new nyc until this evening, have a few things to patch.

**Comment by jseminck** [comment]
Thanks a lot @bcoe! We're not in a hurry to have this, just wanted to know that it was being considered. Keep up the good work. 👍

**Comment by bcoe** [comment]
@jseminck, @tuckerconnelly give `nyc@next` a spin, the next release candidate has these fixes:

`npm cache clear; npm i nyc@next`

Give it a spin, and let me know if it does the trick for you; I'd also love an extra set of eyes on the `include`/`exclude` logic, as I've released some breaking changes:

https://github.com/istanbuljs/nyc/blob/master/CHANGELOG.md#breaking-changes

**Comment by jseminck** [comment]
My issue is fixed and our code coverage is working again. We're using `babel-plugin-istanbul` which depends on this, and it picked up the latest version.

**Pull request merged**
